# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'displayGUI_gpx.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1136, 840)
        MainWindow.setMinimumSize(QtCore.QSize(1136, 840))
        MainWindow.setMaximumSize(QtCore.QSize(1136, 840))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.wpt = QtWidgets.QGroupBox(self.centralwidget)
        self.wpt.setGeometry(QtCore.QRect(30, 297, 341, 491))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wpt.setFont(font)
        self.wpt.setFlat(False)
        self.wpt.setCheckable(False)
        self.wpt.setChecked(False)
        self.wpt.setObjectName("wpt")
        self.wpt_name = QtWidgets.QLabel(self.wpt)
        self.wpt_name.setGeometry(QtCore.QRect(20, 40, 41, 21))
        self.wpt_name.setObjectName("wpt_name")
        self.wpt_name_text = QtWidgets.QLineEdit(self.wpt)
        self.wpt_name_text.setGeometry(QtCore.QRect(70, 40, 251, 21))
        self.wpt_name_text.setObjectName("wpt_name_text")
        self.wpt_desc = QtWidgets.QLabel(self.wpt)
        self.wpt_desc.setGeometry(QtCore.QRect(20, 80, 41, 21))
        self.wpt_desc.setObjectName("wpt_desc")
        self.wpt_desc_text = QtWidgets.QLineEdit(self.wpt)
        self.wpt_desc_text.setGeometry(QtCore.QRect(70, 80, 251, 21))
        self.wpt_desc_text.setObjectName("wpt_desc_text")
        self.wpt_list_display = QtWidgets.QListWidget(self.wpt)
        self.wpt_list_display.setGeometry(QtCore.QRect(20, 150, 301, 281))
        self.wpt_list_display.setObjectName("wpt_list_display")
        self.wpt_list = QtWidgets.QLabel(self.wpt)
        self.wpt_list.setGeometry(QtCore.QRect(20, 120, 131, 21))
        self.wpt_list.setObjectName("wpt_list")
        self.wpt_add_wpt = QtWidgets.QPushButton(self.wpt)
        self.wpt_add_wpt.setGeometry(QtCore.QRect(130, 450, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wpt_add_wpt.setFont(font)
        self.wpt_add_wpt.setObjectName("wpt_add_wpt")
        self.rte = QtWidgets.QGroupBox(self.centralwidget)
        self.rte.setGeometry(QtCore.QRect(400, 297, 341, 491))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rte.setFont(font)
        self.rte.setObjectName("rte")
        self.rte_name_text = QtWidgets.QLineEdit(self.rte)
        self.rte_name_text.setGeometry(QtCore.QRect(70, 40, 251, 21))
        self.rte_name_text.setObjectName("rte_name_text")
        self.rte_name = QtWidgets.QLabel(self.rte)
        self.rte_name.setGeometry(QtCore.QRect(20, 40, 41, 21))
        self.rte_name.setObjectName("rte_name")
        self.rte_desc = QtWidgets.QLabel(self.rte)
        self.rte_desc.setGeometry(QtCore.QRect(20, 80, 41, 21))
        self.rte_desc.setObjectName("rte_desc")
        self.rte_desc_text = QtWidgets.QLineEdit(self.rte)
        self.rte_desc_text.setGeometry(QtCore.QRect(70, 80, 251, 21))
        self.rte_desc_text.setObjectName("rte_desc_text")
        self.rte_add_rte = QtWidgets.QPushButton(self.rte)
        self.rte_add_rte.setGeometry(QtCore.QRect(140, 120, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rte_add_rte.setFont(font)
        self.rte_add_rte.setObjectName("rte_add_rte")
        self.rte_select_list = QtWidgets.QComboBox(self.rte)
        self.rte_select_list.setGeometry(QtCore.QRect(70, 160, 251, 20))
        self.rte_select_list.setObjectName("rte_select_list")
        self.rte_list = QtWidgets.QLabel(self.rte)
        self.rte_list.setGeometry(QtCore.QRect(20, 160, 41, 21))
        self.rte_list.setObjectName("rte_list")
        self.rte_wpt_name_text = QtWidgets.QLineEdit(self.rte)
        self.rte_wpt_name_text.setGeometry(QtCore.QRect(70, 200, 251, 21))
        self.rte_wpt_name_text.setObjectName("rte_wpt_name_text")
        self.rte_wpt_name = QtWidgets.QLabel(self.rte)
        self.rte_wpt_name.setGeometry(QtCore.QRect(20, 200, 41, 21))
        self.rte_wpt_name.setObjectName("rte_wpt_name")
        self.rte_wpt_desc_text = QtWidgets.QLineEdit(self.rte)
        self.rte_wpt_desc_text.setGeometry(QtCore.QRect(70, 240, 251, 21))
        self.rte_wpt_desc_text.setObjectName("rte_wpt_desc_text")
        self.rte_wpt_desc = QtWidgets.QLabel(self.rte)
        self.rte_wpt_desc.setGeometry(QtCore.QRect(20, 240, 41, 21))
        self.rte_wpt_desc.setObjectName("rte_wpt_desc")
        self.rte_add_rte_wpt = QtWidgets.QPushButton(self.rte)
        self.rte_add_rte_wpt.setGeometry(QtCore.QRect(130, 450, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rte_add_rte_wpt.setFont(font)
        self.rte_add_rte_wpt.setObjectName("rte_add_rte_wpt")
        self.rte_wpt_list_display = QtWidgets.QListWidget(self.rte)
        self.rte_wpt_list_display.setGeometry(QtCore.QRect(20, 310, 301, 121))
        self.rte_wpt_list_display.setObjectName("rte_wpt_list_display")
        self.rte_wpt_list = QtWidgets.QLabel(self.rte)
        self.rte_wpt_list.setGeometry(QtCore.QRect(20, 280, 131, 21))
        self.rte_wpt_list.setObjectName("rte_wpt_list")
        self.trk = QtWidgets.QGroupBox(self.centralwidget)
        self.trk.setGeometry(QtCore.QRect(770, 297, 341, 491))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.trk.setFont(font)
        self.trk.setObjectName("trk")
        self.trk_name = QtWidgets.QLabel(self.trk)
        self.trk_name.setGeometry(QtCore.QRect(20, 40, 41, 21))
        self.trk_name.setObjectName("trk_name")
        self.trk_desc = QtWidgets.QLabel(self.trk)
        self.trk_desc.setGeometry(QtCore.QRect(20, 80, 41, 21))
        self.trk_desc.setObjectName("trk_desc")
        self.trk_desc_text = QtWidgets.QLineEdit(self.trk)
        self.trk_desc_text.setGeometry(QtCore.QRect(70, 80, 251, 21))
        self.trk_desc_text.setObjectName("trk_desc_text")
        self.trk_name_text = QtWidgets.QLineEdit(self.trk)
        self.trk_name_text.setGeometry(QtCore.QRect(70, 40, 251, 21))
        self.trk_name_text.setObjectName("trk_name_text")
        self.add_trk = QtWidgets.QPushButton(self.trk)
        self.add_trk.setGeometry(QtCore.QRect(140, 120, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_trk.setFont(font)
        self.add_trk.setObjectName("add_trk")
        self.trk_record_interval = QtWidgets.QGroupBox(self.trk)
        self.trk_record_interval.setGeometry(QtCore.QRect(10, 200, 321, 101))
        self.trk_record_interval.setObjectName("trk_record_interval")
        self.trk_record_interval_time = QtWidgets.QRadioButton(self.trk_record_interval)
        self.trk_record_interval_time.setGeometry(QtCore.QRect(20, 20, 89, 31))
        self.trk_record_interval_time.setChecked(True)
        self.trk_record_interval_time.setObjectName("trk_record_interval_time")
        self.trk_record_interval_dis = QtWidgets.QRadioButton(self.trk_record_interval)
        self.trk_record_interval_dis.setGeometry(QtCore.QRect(20, 60, 89, 31))
        self.trk_record_interval_dis.setObjectName("trk_record_interval_dis")
        self.trk_record_interval_time_set = QtWidgets.QDoubleSpinBox(self.trk_record_interval)
        self.trk_record_interval_time_set.setGeometry(QtCore.QRect(120, 20, 191, 31))
        self.trk_record_interval_time_set.setMinimum(0.01)
        self.trk_record_interval_time_set.setSingleStep(0.1)
        self.trk_record_interval_time_set.setProperty("value", 0.2)
        self.trk_record_interval_time_set.setObjectName("trk_record_interval_time_set")
        self.trk_record_interval_dis_set = QtWidgets.QDoubleSpinBox(self.trk_record_interval)
        self.trk_record_interval_dis_set.setGeometry(QtCore.QRect(120, 60, 191, 31))
        self.trk_record_interval_dis_set.setMinimum(0.01)
        self.trk_record_interval_dis_set.setSingleStep(0.1)
        self.trk_record_interval_dis_set.setProperty("value", 0.2)
        self.trk_record_interval_dis_set.setObjectName("trk_record_interval_dis_set")
        self.trk_extensions = QtWidgets.QGroupBox(self.trk)
        self.trk_extensions.setGeometry(QtCore.QRect(10, 310, 321, 91))
        self.trk_extensions.setAutoFillBackground(False)
        self.trk_extensions.setInputMethodHints(QtCore.Qt.ImhNone)
        self.trk_extensions.setCheckable(False)
        self.trk_extensions.setObjectName("trk_extensions")
        self.trk_extensions_velocity = QtWidgets.QCheckBox(self.trk_extensions)
        self.trk_extensions_velocity.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.trk_extensions_velocity.setObjectName("trk_extensions_velocity")
        self.trk_extensions_status = QtWidgets.QCheckBox(self.trk_extensions)
        self.trk_extensions_status.setGeometry(QtCore.QRect(90, 30, 71, 21))
        self.trk_extensions_status.setObjectName("trk_extensions_status")
        self.trk_extensions_time_stamp = QtWidgets.QCheckBox(self.trk_extensions)
        self.trk_extensions_time_stamp.setGeometry(QtCore.QRect(250, 30, 71, 21))
        self.trk_extensions_time_stamp.setObjectName("trk_extensions_time_stamp")
        self.trk_extensions_heading = QtWidgets.QCheckBox(self.trk_extensions)
        self.trk_extensions_heading.setGeometry(QtCore.QRect(10, 60, 71, 21))
        self.trk_extensions_heading.setObjectName("trk_extensions_heading")
        self.trk_extensions_pitch = QtWidgets.QCheckBox(self.trk_extensions)
        self.trk_extensions_pitch.setGeometry(QtCore.QRect(90, 60, 71, 21))
        self.trk_extensions_pitch.setObjectName("trk_extensions_pitch")
        self.trk_extensions_roll = QtWidgets.QCheckBox(self.trk_extensions)
        self.trk_extensions_roll.setGeometry(QtCore.QRect(170, 60, 71, 21))
        self.trk_extensions_roll.setObjectName("trk_extensions_roll")
        self.trk_extensions_altitude = QtWidgets.QCheckBox(self.trk_extensions)
        self.trk_extensions_altitude.setGeometry(QtCore.QRect(170, 30, 71, 21))
        self.trk_extensions_altitude.setObjectName("trk_extensions_altitude")
        self.trk_extensions_time = QtWidgets.QCheckBox(self.trk_extensions)
        self.trk_extensions_time.setGeometry(QtCore.QRect(250, 60, 71, 21))
        self.trk_extensions_time.setObjectName("trk_extensions_time")
        self.trk_count = QtWidgets.QLabel(self.trk)
        self.trk_count.setGeometry(QtCore.QRect(20, 410, 54, 21))
        self.trk_count.setObjectName("trk_count")
        self.trk_count_number = QtWidgets.QLabel(self.trk)
        self.trk_count_number.setGeometry(QtCore.QRect(90, 410, 151, 21))
        self.trk_count_number.setObjectName("trk_count_number")
        self.trk_begin = QtWidgets.QPushButton(self.trk)
        self.trk_begin.setGeometry(QtCore.QRect(10, 450, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trk_begin.setFont(font)
        self.trk_begin.setCheckable(False)
        self.trk_begin.setObjectName("trk_begin")
        self.trk_pause = QtWidgets.QPushButton(self.trk)
        self.trk_pause.setGeometry(QtCore.QRect(90, 450, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trk_pause.setFont(font)
        self.trk_pause.setCheckable(False)
        self.trk_pause.setObjectName("trk_pause")
        self.trk_cancel = QtWidgets.QPushButton(self.trk)
        self.trk_cancel.setGeometry(QtCore.QRect(170, 450, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trk_cancel.setFont(font)
        self.trk_cancel.setObjectName("trk_cancel")
        self.trk_export_csv = QtWidgets.QPushButton(self.trk)
        self.trk_export_csv.setGeometry(QtCore.QRect(250, 450, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trk_export_csv.setFont(font)
        self.trk_export_csv.setObjectName("trk_export_csv")
        self.trk_select_list = QtWidgets.QComboBox(self.trk)
        self.trk_select_list.setGeometry(QtCore.QRect(70, 160, 251, 20))
        self.trk_select_list.setObjectName("trk_select_list")
        self.trk_select = QtWidgets.QLabel(self.trk)
        self.trk_select.setGeometry(QtCore.QRect(20, 160, 41, 21))
        self.trk_select.setObjectName("trk_select")
        self.trk_name.raise_()
        self.trk_desc.raise_()
        self.trk_desc_text.raise_()
        self.add_trk.raise_()
        self.trk_record_interval.raise_()
        self.trk_extensions.raise_()
        self.trk_count.raise_()
        self.trk_count_number.raise_()
        self.trk_begin.raise_()
        self.trk_pause.raise_()
        self.trk_cancel.raise_()
        self.trk_export_csv.raise_()
        self.trk_select_list.raise_()
        self.trk_select.raise_()
        self.trk_name_text.raise_()
        self.metadata = QtWidgets.QGroupBox(self.centralwidget)
        self.metadata.setGeometry(QtCore.QRect(30, 107, 341, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.metadata.setFont(font)
        self.metadata.setObjectName("metadata")
        self.metadata_name = QtWidgets.QLabel(self.metadata)
        self.metadata_name.setGeometry(QtCore.QRect(20, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.metadata_name.setFont(font)
        self.metadata_name.setObjectName("metadata_name")
        self.metadata_desc = QtWidgets.QLabel(self.metadata)
        self.metadata_desc.setGeometry(QtCore.QRect(20, 60, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.metadata_desc.setFont(font)
        self.metadata_desc.setObjectName("metadata_desc")
        self.metadata_author = QtWidgets.QLabel(self.metadata)
        self.metadata_author.setGeometry(QtCore.QRect(20, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.metadata_author.setFont(font)
        self.metadata_author.setObjectName("metadata_author")
        self.metadata_name_text = QtWidgets.QLineEdit(self.metadata)
        self.metadata_name_text.setGeometry(QtCore.QRect(70, 30, 251, 21))
        self.metadata_name_text.setObjectName("metadata_name_text")
        self.metadata_desc_text = QtWidgets.QLineEdit(self.metadata)
        self.metadata_desc_text.setGeometry(QtCore.QRect(70, 60, 251, 21))
        self.metadata_desc_text.setObjectName("metadata_desc_text")
        self.metadata_author_text = QtWidgets.QLineEdit(self.metadata)
        self.metadata_author_text.setGeometry(QtCore.QRect(70, 90, 251, 21))
        self.metadata_author_text.setObjectName("metadata_author_text")
        self.metadata_create = QtWidgets.QPushButton(self.metadata)
        self.metadata_create.setGeometry(QtCore.QRect(130, 130, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.metadata_create.setFont(font)
        self.metadata_create.setObjectName("metadata_create")
        self.info = QtWidgets.QGroupBox(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(400, 107, 341, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.info_lon = QtWidgets.QLabel(self.info)
        self.info_lon.setGeometry(QtCore.QRect(20, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_lon.setFont(font)
        self.info_lon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_lon.setObjectName("info_lon")
        self.info_lon_text = QtWidgets.QLabel(self.info)
        self.info_lon_text.setGeometry(QtCore.QRect(70, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_lon_text.setFont(font)
        self.info_lon_text.setObjectName("info_lon_text")
        self.info_lat = QtWidgets.QLabel(self.info)
        self.info_lat.setGeometry(QtCore.QRect(20, 60, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_lat.setFont(font)
        self.info_lat.setObjectName("info_lat")
        self.info_velocity = QtWidgets.QLabel(self.info)
        self.info_velocity.setGeometry(QtCore.QRect(20, 120, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_velocity.setFont(font)
        self.info_velocity.setObjectName("info_velocity")
        self.info_status = QtWidgets.QLabel(self.info)
        self.info_status.setGeometry(QtCore.QRect(20, 150, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_status.setFont(font)
        self.info_status.setObjectName("info_status")
        self.info_lat_text = QtWidgets.QLabel(self.info)
        self.info_lat_text.setGeometry(QtCore.QRect(70, 60, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_lat_text.setFont(font)
        self.info_lat_text.setObjectName("info_lat_text")
        self.info_velocity_text = QtWidgets.QLabel(self.info)
        self.info_velocity_text.setGeometry(QtCore.QRect(70, 120, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_velocity_text.setFont(font)
        self.info_velocity_text.setObjectName("info_velocity_text")
        self.info_status_text = QtWidgets.QLabel(self.info)
        self.info_status_text.setGeometry(QtCore.QRect(70, 150, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_status_text.setFont(font)
        self.info_status_text.setObjectName("info_status_text")
        self.info_heading = QtWidgets.QLabel(self.info)
        self.info_heading.setGeometry(QtCore.QRect(190, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_heading.setFont(font)
        self.info_heading.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_heading.setObjectName("info_heading")
        self.info_heading_text = QtWidgets.QLabel(self.info)
        self.info_heading_text.setGeometry(QtCore.QRect(250, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_heading_text.setFont(font)
        self.info_heading_text.setObjectName("info_heading_text")
        self.info_pitch_text = QtWidgets.QLabel(self.info)
        self.info_pitch_text.setGeometry(QtCore.QRect(250, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_pitch_text.setFont(font)
        self.info_pitch_text.setObjectName("info_pitch_text")
        self.info_pitch = QtWidgets.QLabel(self.info)
        self.info_pitch.setGeometry(QtCore.QRect(190, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_pitch.setFont(font)
        self.info_pitch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_pitch.setObjectName("info_pitch")
        self.info_roll_text = QtWidgets.QLabel(self.info)
        self.info_roll_text.setGeometry(QtCore.QRect(250, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_roll_text.setFont(font)
        self.info_roll_text.setObjectName("info_roll_text")
        self.info_roll = QtWidgets.QLabel(self.info)
        self.info_roll.setGeometry(QtCore.QRect(190, 90, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_roll.setFont(font)
        self.info_roll.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_roll.setObjectName("info_roll")
        self.info_satellite_number_text = QtWidgets.QLabel(self.info)
        self.info_satellite_number_text.setGeometry(QtCore.QRect(250, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_satellite_number_text.setFont(font)
        self.info_satellite_number_text.setObjectName("info_satellite_number_text")
        self.info_satellite_number = QtWidgets.QLabel(self.info)
        self.info_satellite_number.setGeometry(QtCore.QRect(190, 120, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_satellite_number.setFont(font)
        self.info_satellite_number.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_satellite_number.setObjectName("info_satellite_number")
        self.info_time_stamp = QtWidgets.QLabel(self.info)
        self.info_time_stamp.setGeometry(QtCore.QRect(190, 150, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_time_stamp.setFont(font)
        self.info_time_stamp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_time_stamp.setObjectName("info_time_stamp")
        self.info_time_stamp_text = QtWidgets.QLabel(self.info)
        self.info_time_stamp_text.setGeometry(QtCore.QRect(250, 150, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_time_stamp_text.setFont(font)
        self.info_time_stamp_text.setObjectName("info_time_stamp_text")
        self.info_altitude = QtWidgets.QLabel(self.info)
        self.info_altitude.setGeometry(QtCore.QRect(20, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_altitude.setFont(font)
        self.info_altitude.setObjectName("info_altitude")
        self.info_altitude_text = QtWidgets.QLabel(self.info)
        self.info_altitude_text.setGeometry(QtCore.QRect(70, 90, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_altitude_text.setFont(font)
        self.info_altitude_text.setObjectName("info_altitude_text")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 40, 1101, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(20, 10, 1091, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 80, 1101, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.begin = QtWidgets.QPushButton(self.centralwidget)
        self.begin.setGeometry(QtCore.QRect(680, 60, 75, 23))
        self.begin.setCheckable(True)
        self.begin.setObjectName("begin")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(770, 60, 75, 23))
        self.stop.setObjectName("stop")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(860, 60, 75, 23))
        self.cancel.setObjectName("cancel")
        self.export_gpx = QtWidgets.QPushButton(self.centralwidget)
        self.export_gpx.setGeometry(QtCore.QRect(1040, 60, 75, 23))
        self.export_gpx.setObjectName("export_gpx")
        self.map_display = QtWidgets.QLabel(self.centralwidget)
        self.map_display.setGeometry(QtCore.QRect(770, 110, 341, 161))
        self.map_display.setFrameShape(QtWidgets.QFrame.Box)
        self.map_display.setAlignment(QtCore.Qt.AlignCenter)
        self.map_display.setObjectName("map_display")
        self.print_gpx = QtWidgets.QPushButton(self.centralwidget)
        self.print_gpx.setGeometry(QtCore.QRect(950, 60, 75, 23))
        self.print_gpx.setObjectName("print_gpx")
        self.port_select = QtWidgets.QLabel(self.centralwidget)
        self.port_select.setGeometry(QtCore.QRect(20, 60, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.port_select.setFont(font)
        self.port_select.setObjectName("port_select")
        self.port_select_list = QtWidgets.QComboBox(self.centralwidget)
        self.port_select_list.setGeometry(QtCore.QRect(90, 60, 201, 20))
        self.port_select_list.setObjectName("port_select_list")
        self.port_select_baudrate_list = QtWidgets.QComboBox(self.centralwidget)
        self.port_select_baudrate_list.setGeometry(QtCore.QRect(360, 60, 131, 20))
        self.port_select_baudrate_list.setObjectName("port_select_baudrate_list")
        self.port_select_baudrate_list.addItem("")
        self.port_select_baudrate_list.addItem("")
        self.port_select_baudrate_list.addItem("")
        self.port_select_baudrate_list.addItem("")
        self.port_select_baudrate_list.addItem("")
        self.port_select_baudrate_list.addItem("")
        self.port_select_baudrate_list.addItem("")
        self.port_select_baudrate = QtWidgets.QLabel(self.centralwidget)
        self.port_select_baudrate.setGeometry(QtCore.QRect(310, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.port_select_baudrate.setFont(font)
        self.port_select_baudrate.setObjectName("port_select_baudrate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.port_select_list, self.port_select_baudrate_list)
        MainWindow.setTabOrder(self.port_select_baudrate_list, self.begin)
        MainWindow.setTabOrder(self.begin, self.stop)
        MainWindow.setTabOrder(self.stop, self.cancel)
        MainWindow.setTabOrder(self.cancel, self.print_gpx)
        MainWindow.setTabOrder(self.print_gpx, self.export_gpx)
        MainWindow.setTabOrder(self.export_gpx, self.metadata_name_text)
        MainWindow.setTabOrder(self.metadata_name_text, self.metadata_desc_text)
        MainWindow.setTabOrder(self.metadata_desc_text, self.metadata_author_text)
        MainWindow.setTabOrder(self.metadata_author_text, self.metadata_create)
        MainWindow.setTabOrder(self.metadata_create, self.wpt_name_text)
        MainWindow.setTabOrder(self.wpt_name_text, self.wpt_desc_text)
        MainWindow.setTabOrder(self.wpt_desc_text, self.wpt_list_display)
        MainWindow.setTabOrder(self.wpt_list_display, self.wpt_add_wpt)
        MainWindow.setTabOrder(self.wpt_add_wpt, self.rte_name_text)
        MainWindow.setTabOrder(self.rte_name_text, self.rte_desc_text)
        MainWindow.setTabOrder(self.rte_desc_text, self.rte_add_rte)
        MainWindow.setTabOrder(self.rte_add_rte, self.rte_select_list)
        MainWindow.setTabOrder(self.rte_select_list, self.rte_wpt_name_text)
        MainWindow.setTabOrder(self.rte_wpt_name_text, self.rte_wpt_desc_text)
        MainWindow.setTabOrder(self.rte_wpt_desc_text, self.rte_wpt_list_display)
        MainWindow.setTabOrder(self.rte_wpt_list_display, self.rte_add_rte_wpt)
        MainWindow.setTabOrder(self.rte_add_rte_wpt, self.trk_name_text)
        MainWindow.setTabOrder(self.trk_name_text, self.trk_desc_text)
        MainWindow.setTabOrder(self.trk_desc_text, self.add_trk)
        MainWindow.setTabOrder(self.add_trk, self.trk_select_list)
        MainWindow.setTabOrder(self.trk_select_list, self.trk_record_interval_time)
        MainWindow.setTabOrder(self.trk_record_interval_time, self.trk_record_interval_time_set)
        MainWindow.setTabOrder(self.trk_record_interval_time_set, self.trk_record_interval_dis)
        MainWindow.setTabOrder(self.trk_record_interval_dis, self.trk_record_interval_dis_set)
        MainWindow.setTabOrder(self.trk_record_interval_dis_set, self.trk_extensions_velocity)
        MainWindow.setTabOrder(self.trk_extensions_velocity, self.trk_extensions_status)
        MainWindow.setTabOrder(self.trk_extensions_status, self.trk_extensions_altitude)
        MainWindow.setTabOrder(self.trk_extensions_altitude, self.trk_extensions_time_stamp)
        MainWindow.setTabOrder(self.trk_extensions_time_stamp, self.trk_extensions_heading)
        MainWindow.setTabOrder(self.trk_extensions_heading, self.trk_extensions_pitch)
        MainWindow.setTabOrder(self.trk_extensions_pitch, self.trk_extensions_roll)
        MainWindow.setTabOrder(self.trk_extensions_roll, self.trk_extensions_time)
        MainWindow.setTabOrder(self.trk_extensions_time, self.trk_begin)
        MainWindow.setTabOrder(self.trk_begin, self.trk_pause)
        MainWindow.setTabOrder(self.trk_pause, self.trk_cancel)
        MainWindow.setTabOrder(self.trk_cancel, self.trk_export_csv)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.wpt.setTitle(_translate("MainWindow", "航路点"))
        self.wpt_name.setText(_translate("MainWindow", "名称:"))
        self.wpt_desc.setText(_translate("MainWindow", "描述:"))
        self.wpt_list.setText(_translate("MainWindow", "航路点列表:"))
        self.wpt_add_wpt.setText(_translate("MainWindow", "添加"))
        self.rte.setTitle(_translate("MainWindow", "航迹点"))
        self.rte_name.setText(_translate("MainWindow", "名称:"))
        self.rte_desc.setText(_translate("MainWindow", "描述:"))
        self.rte_add_rte.setText(_translate("MainWindow", "添加航迹"))
        self.rte_list.setText(_translate("MainWindow", "航迹:"))
        self.rte_wpt_name.setText(_translate("MainWindow", "名称:"))
        self.rte_wpt_desc.setText(_translate("MainWindow", "描述:"))
        self.rte_add_rte_wpt.setText(_translate("MainWindow", "添加航迹点"))
        self.rte_wpt_list.setText(_translate("MainWindow", "航迹点列表:"))
        self.trk.setTitle(_translate("MainWindow", "轨迹点"))
        self.trk_name.setText(_translate("MainWindow", "名称:"))
        self.trk_desc.setText(_translate("MainWindow", "描述:"))
        self.add_trk.setText(_translate("MainWindow", "添加轨迹"))
        self.trk_record_interval.setTitle(_translate("MainWindow", "轨迹点间隔"))
        self.trk_record_interval_time.setText(_translate("MainWindow", "按时间(s)"))
        self.trk_record_interval_dis.setText(_translate("MainWindow", "按距离(m)"))
        self.trk_extensions.setTitle(_translate("MainWindow", "附加信息"))
        self.trk_extensions_velocity.setText(_translate("MainWindow", "速  度"))
        self.trk_extensions_status.setText(_translate("MainWindow", "状  态"))
        self.trk_extensions_time_stamp.setText(_translate("MainWindow", "时间戳"))
        self.trk_extensions_heading.setText(_translate("MainWindow", "航向角"))
        self.trk_extensions_pitch.setText(_translate("MainWindow", "俯仰角"))
        self.trk_extensions_roll.setText(_translate("MainWindow", "翻滚角"))
        self.trk_extensions_altitude.setText(_translate("MainWindow", "海  拔"))
        self.trk_extensions_time.setText(_translate("MainWindow", "时  间"))
        self.trk_count.setText(_translate("MainWindow", "已记录:"))
        self.trk_count_number.setText(_translate("MainWindow", "0"))
        self.trk_begin.setText(_translate("MainWindow", "开始"))
        self.trk_pause.setText(_translate("MainWindow", "暂停"))
        self.trk_cancel.setText(_translate("MainWindow", "取消"))
        self.trk_export_csv.setText(_translate("MainWindow", "导出CSV"))
        self.trk_select.setText(_translate("MainWindow", "轨迹:"))
        self.metadata.setTitle(_translate("MainWindow", "元数据"))
        self.metadata_name.setText(_translate("MainWindow", "名称:"))
        self.metadata_desc.setText(_translate("MainWindow", "描述:"))
        self.metadata_author.setText(_translate("MainWindow", "作者:"))
        self.metadata_create.setText(_translate("MainWindow", "生成"))
        self.info.setTitle(_translate("MainWindow", "信息"))
        self.info_lon.setText(_translate("MainWindow", "经度:"))
        self.info_lon_text.setText(_translate("MainWindow", "0"))
        self.info_lat.setText(_translate("MainWindow", "纬度:"))
        self.info_velocity.setText(_translate("MainWindow", "速度:"))
        self.info_status.setText(_translate("MainWindow", "状态:"))
        self.info_lat_text.setText(_translate("MainWindow", "0"))
        self.info_velocity_text.setText(_translate("MainWindow", "0"))
        self.info_status_text.setText(_translate("MainWindow", "0"))
        self.info_heading.setText(_translate("MainWindow", "航向角:"))
        self.info_heading_text.setText(_translate("MainWindow", "0"))
        self.info_pitch_text.setText(_translate("MainWindow", "0"))
        self.info_pitch.setText(_translate("MainWindow", "俯仰角:"))
        self.info_roll_text.setText(_translate("MainWindow", "0"))
        self.info_roll.setText(_translate("MainWindow", "翻滚角:"))
        self.info_satellite_number_text.setText(_translate("MainWindow", "0"))
        self.info_satellite_number.setText(_translate("MainWindow", "卫星数:"))
        self.info_time_stamp.setText(_translate("MainWindow", "时间戳:"))
        self.info_time_stamp_text.setText(_translate("MainWindow", "0"))
        self.info_altitude.setText(_translate("MainWindow", "海拔:"))
        self.info_altitude_text.setText(_translate("MainWindow", "0"))
        self.title.setText(_translate("MainWindow", "轨  迹  录  制"))
        self.begin.setText(_translate("MainWindow", "开始"))
        self.stop.setText(_translate("MainWindow", "停止"))
        self.cancel.setText(_translate("MainWindow", "取消"))
        self.export_gpx.setText(_translate("MainWindow", "导出GPX"))
        self.map_display.setText(_translate("MainWindow", "TextLabel"))
        self.print_gpx.setText(_translate("MainWindow", "打印GPX"))
        self.port_select.setText(_translate("MainWindow", "串口选择:"))
        self.port_select_baudrate_list.setCurrentText(_translate("MainWindow", "9600"))
        self.port_select_baudrate_list.setItemText(0, _translate("MainWindow", "9600"))
        self.port_select_baudrate_list.setItemText(1, _translate("MainWindow", "19200"))
        self.port_select_baudrate_list.setItemText(2, _translate("MainWindow", "38400"))
        self.port_select_baudrate_list.setItemText(3, _translate("MainWindow", "57600"))
        self.port_select_baudrate_list.setItemText(4, _translate("MainWindow", "115200"))
        self.port_select_baudrate_list.setItemText(5, _translate("MainWindow", "230400"))
        self.port_select_baudrate_list.setItemText(6, _translate("MainWindow", "460800"))
        self.port_select_baudrate.setText(_translate("MainWindow", "波特率:"))
